SELECT
    'CUSTOMERS' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    COUNT_IF(CUSTOMER_ID IS NULL) AS NULL_CUSTOMER_ID,
    COUNT(DISTINCT CUSTOMER_ID) AS DISTINCT_CUSTOMER_ID
FROM BANKING_DQ_DB.RAW.CUSTOMERS

UNION ALL

SELECT
    'ACCOUNTS',
    COUNT(*),
    COUNT_IF(ACCOUNT_ID IS NULL),
    COUNT(DISTINCT ACCOUNT_ID)
FROM BANKING_DQ_DB.RAW.ACCOUNTS

UNION ALL

SELECT
    'TRANSACTIONS',
    COUNT(*),
    COUNT_IF(TRANSACTION_ID IS NULL),
    COUNT(DISTINCT TRANSACTION_ID)
FROM BANKING_DQ_DB.RAW.TRANSACTIONS

UNION ALL

SELECT
    'LOAN_APPLICATIONS',
    COUNT(*),
    COUNT_IF(APPLICATION_ID IS NULL),
    COUNT(DISTINCT APPLICATION_ID)
FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS;