SELECT
    'CUSTOMERS' AS TABLE_NAME,
    'CUSTOMER_ID_NOT_NULL' AS RULE_NAME,
    COUNT_IF(CUSTOMER_ID IS NULL) AS FAILED_RECORDS,
    IFF(COUNT_IF(CUSTOMER_ID IS NULL) = 0, 'PASS', 'FAIL') AS STATUS
FROM BANKING_DQ_DB.RAW.CUSTOMERS

UNION ALL

SELECT
    'CUSTOMERS',
    'CUSTOMER_ID_UNIQUE',
    COUNT(*) - COUNT(DISTINCT CUSTOMER_ID),
    IFF(COUNT(*) = COUNT(DISTINCT CUSTOMER_ID), 'PASS', 'FAIL')
FROM BANKING_DQ_DB.RAW.CUSTOMERS

UNION ALL

SELECT
    'ACCOUNTS',
    'ACCOUNT_ID_NOT_NULL',
    COUNT_IF(ACCOUNT_ID IS NULL),
    IFF(COUNT_IF(ACCOUNT_ID IS NULL) = 0, 'PASS', 'FAIL')
FROM BANKING_DQ_DB.RAW.ACCOUNTS

UNION ALL

SELECT
    'ACCOUNTS',
    'ACCOUNT_ID_UNIQUE',
    COUNT(*) - COUNT(DISTINCT ACCOUNT_ID),
    IFF(COUNT(*) = COUNT(DISTINCT ACCOUNT_ID), 'PASS', 'FAIL')
FROM BANKING_DQ_DB.RAW.ACCOUNTS

UNION ALL

SELECT
    'ACCOUNTS',
    'BALANCE_NOT_NULL',
    COUNT_IF(BALANCE IS NULL),
    IFF(COUNT_IF(BALANCE IS NULL) = 0, 'PASS', 'FAIL')
FROM BANKING_DQ_DB.RAW.ACCOUNTS

UNION ALL

SELECT
    'ACCOUNTS',
    'BALANCE_NON_NEGATIVE',
    COUNT_IF(BALANCE < 0),
    IFF(COUNT_IF(BALANCE < 0) = 0, 'PASS', 'FAIL')
FROM BANKING_DQ_DB.RAW.ACCOUNTS

UNION ALL

SELECT
    'TRANSACTIONS',
    'TRANSACTION_ID_UNIQUE',
    COUNT(*) - COUNT(DISTINCT TRANSACTION_ID),
    IFF(COUNT(*) = COUNT(DISTINCT TRANSACTION_ID), 'PASS', 'FAIL')
FROM BANKING_DQ_DB.RAW.TRANSACTIONS

UNION ALL

SELECT
    'TRANSACTIONS',
    'AMOUNT_NOT_NULL',
    COUNT_IF(AMOUNT IS NULL),
    IFF(COUNT_IF(AMOUNT IS NULL) = 0, 'PASS', 'FAIL')
FROM BANKING_DQ_DB.RAW.TRANSACTIONS

UNION ALL

SELECT
    'LOAN_APPLICATIONS',
    'APPLICATION_ID_UNIQUE',
    COUNT(*) - COUNT(DISTINCT APPLICATION_ID),
    IFF(COUNT(*) = COUNT(DISTINCT APPLICATION_ID), 'PASS', 'FAIL')
FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS

UNION ALL

SELECT
    'LOAN_APPLICATIONS',
    'LOAN_AMOUNT_NOT_NULL',
    COUNT_IF(LOAN_AMOUNT IS NULL),
    IFF(COUNT_IF(LOAN_AMOUNT IS NULL) = 0, 'PASS', 'FAIL')
FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS;