-- 1. Invalid negative balance
INSERT INTO BANKING_DQ_DB.RAW.ACCOUNTS
    (ACCOUNT_ID, CUSTOMER_ID, BRANCH_ID, ACCOUNT_TYPE, ACCOUNT_STATUS, BALANCE)
VALUES
    (999, 1, 101, 'CHECKING', 'ACTIVE', -500);

-- 2. Duplicate transaction ID
INSERT INTO BANKING_DQ_DB.RAW.TRANSACTIONS
    (TRANSACTION_ID, ACCOUNT_ID, TRANSACTION_TYPE, AMOUNT, TRANSACTION_STATUS)
SELECT
    TRANSACTION_ID,
    ACCOUNT_ID,
    TRANSACTION_TYPE,
    AMOUNT,
    TRANSACTION_STATUS
FROM BANKING_DQ_DB.RAW.TRANSACTIONS
WHERE TRANSACTION_ID = 1001;

INSERT INTO BANKING_DQ_DB.RAW.TRANSACTIONS
    (TRANSACTION_ID, ACCOUNT_ID, TRANSACTION_TYPE, AMOUNT, TRANSACTION_STATUS)
VALUES
    (1001, 101, 'DEPOSIT', 500, 'COMPLETED');

-- 3. Null transaction amount
INSERT INTO BANKING_DQ_DB.RAW.TRANSACTIONS
    (TRANSACTION_ID, ACCOUNT_ID, TRANSACTION_TYPE, AMOUNT, TRANSACTION_STATUS)
VALUES
    (9999, 101, 'WITHDRAWAL', NULL, 'COMPLETED');

-- 4. Null loan amount
INSERT INTO BANKING_DQ_DB.RAW.LOAN_APPLICATIONS
    (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, LOAN_AMOUNT, APPLICATION_STATUS)
VALUES
    (999, 1, 'PERSONAL', NULL, 'PENDING');