SELECT
    'NEGATIVE_BALANCE' AS ISSUE,
    COUNT(*) AS RECORDS
FROM BANKING_DQ_DB.RAW.ACCOUNTS
WHERE BALANCE < 0

UNION ALL

SELECT
    'DUPLICATE_TRANSACTION_ID',
    COUNT(*) - COUNT(DISTINCT TRANSACTION_ID)
FROM BANKING_DQ_DB.RAW.TRANSACTIONS

UNION ALL

SELECT
    'NULL_TRANSACTION_AMOUNT',
    COUNT(*)
FROM BANKING_DQ_DB.RAW.TRANSACTIONS
WHERE AMOUNT IS NULL

UNION ALL

SELECT
    'NULL_LOAN_AMOUNT',
    COUNT(*)
FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS
WHERE LOAN_AMOUNT IS NULL;

SELECT *
FROM BANKING_DQ_DB.RAW.ACCOUNTS
WHERE ACCOUNT_ID = 999;

SELECT *
FROM BANKING_DQ_DB.RAW.TRANSACTIONS
WHERE TRANSACTION_ID = 1001;

SELECT *
FROM BANKING_DQ_DB.RAW.ACCOUNTS
WHERE ACCOUNT_ID = 999;

SELECT *
FROM BANKING_DQ_DB.RAW.TRANSACTIONS
WHERE TRANSACTION_ID = 1001;

SELECT
    TRANSACTION_ID,
    COUNT(*) AS RECORD_COUNT
FROM BANKING_DQ_DB.RAW.TRANSACTIONS
WHERE TRANSACTION_ID = 1001
GROUP BY TRANSACTION_ID;