/*=============================================================================
  DQ_Framework_Config.sql
  Data Quality Framework — Step 4: Framework Schema, Tables & Rule Loading
  Database: BANKING_DQ_DB  |  Schema: DQ_MONITORING
=============================================================================*/

-- ============================================================================
-- 1. CREATE SCHEMA
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS BANKING_DQ_DB.DQ_MONITORING;
USE DATABASE BANKING_DQ_DB;
USE SCHEMA DQ_MONITORING;

-- ============================================================================
-- 2. CREATE FRAMEWORK TABLES
-- ============================================================================

-- 2a. DQ_RULE_CONFIG — Store all data quality rules
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG (
    RULE_ID         NUMBER          NOT NULL,
    RULE_NAME       VARCHAR(200)    NOT NULL,
    RULE_TYPE       VARCHAR(50)     NOT NULL,
    FREQUENCY       VARCHAR(50)     DEFAULT 'ON_DEMAND',
    CRITICALITY     VARCHAR(20)     NOT NULL,
    DB_NAME         VARCHAR(200),
    TABLE_NM        VARCHAR(200),
    COLUMN_NM       VARCHAR(200),
    RULE_DESCRIPTION VARCHAR(1000),
    RULE_SQL        VARCHAR(5000)   NOT NULL,
    THRESHOLD_VALUE NUMBER(18,4)    DEFAULT 0,
    RULE_DIMENSION  VARCHAR(500),
    IS_ACTIVE       BOOLEAN         DEFAULT TRUE,
    CREATED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DQ_RULE_CONFIG PRIMARY KEY (RULE_ID)
);

-- 2b. DQ_RUN_CONTROL — Track each execution run
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_RUN_CONTROL (
    RUN_ID              NUMBER          NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
    RULE_ID             NUMBER          NOT NULL,
    RUN_START_TIME      TIMESTAMP_NTZ,
    RUN_END_TIME        TIMESTAMP_NTZ,
    RULE_EXEC_RESULT    VARCHAR(20),
    RULE_OUTPUT_VALUE   NUMBER(18,4),
    RUN_STATUS          VARCHAR(20)     DEFAULT 'PENDING',
    TRIGGERED_BY        VARCHAR(100)    DEFAULT 'MANUAL',
    ERROR_MESSAGE       VARCHAR(2000),
    CREATED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DQ_RUN_CONTROL PRIMARY KEY (RUN_ID)
);

-- 2c. DQ_RULE_RESULTS — Store rule-level execution results
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_RESULTS (
    RESULT_ID           NUMBER          NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
    RUN_ID              NUMBER          NOT NULL,
    RULE_ID             NUMBER          NOT NULL,
    DB_NAME             VARCHAR(200),
    TABLE_NAME          VARCHAR(200),
    COLUMN_NAME         VARCHAR(200),
    RULE_NAME           VARCHAR(200),
    RULE_TYPE           VARCHAR(50),
    EXPECTED_VALUE      NUMBER(18,4),
    ACTUAL_VALUE        NUMBER(18,4),
    FAILED_RECORD_COUNT NUMBER(18,0),
    TOTAL_RECORD_COUNT  NUMBER(18,0),
    PASS_PERCENTAGE     NUMBER(7,4),
    RESULT_STATUS       VARCHAR(20),
    SEVERITY            VARCHAR(20),
    ERROR_SAMPLE_QUERY  VARCHAR(5000),
    EXECUTED_AT         TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DQ_RULE_RESULTS PRIMARY KEY (RESULT_ID)
);

-- 2d. DQ_ERROR_RECORDS — Store detailed failed records or samples
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_ERROR_RECORDS (
    ERROR_ID            NUMBER          NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
    RUN_ID              NUMBER          NOT NULL,
    RULE_ID             NUMBER          NOT NULL,
    DB_NAME             VARCHAR(200),
    TABLE_NAME          VARCHAR(200),
    ERROR_RECORD_VARIANT VARIANT,
    ERROR_REASON        VARCHAR(1000),
    CREATED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DQ_ERROR_RECORDS PRIMARY KEY (ERROR_ID)
);

-- 2e. DQ_ANOMALY_RESULTS — Store anomaly detection results
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_ANOMALY_RESULTS (
    ANOMALY_ID          NUMBER          NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
    RUN_ID              NUMBER          NOT NULL,
    DATABASE_NAME       VARCHAR(200),
    SCHEMA_NAME         VARCHAR(200),
    TABLE_NAME          VARCHAR(200),
    METRIC_NAME         VARCHAR(200),
    CURRENT_VALUE       NUMBER(18,4),
    PREVIOUS_VALUE      NUMBER(18,4),
    BASELINE_AVG        NUMBER(18,4),
    BASELINE_STDDEV     NUMBER(18,4),
    ANOMALY_STATUS      VARCHAR(50),
    ANOMALY_REASON      VARCHAR(1000),
    DETECTED_AT         TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DQ_ANOMALY_RESULTS PRIMARY KEY (ANOMALY_ID)
);

-- ============================================================================
-- 3. LOAD RULES INTO DQ_RULE_CONFIG
-- ============================================================================

-- 3a. BRANCHES Rules (1-9)
INSERT ALL
INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES
  (1, 'BR_NULL_BRANCH_ID', 'COMPLETENESS', 'ON_DEMAND', 'HIGH', 'BANKING_DQ_DB.RAW', 'BRANCHES', 'BRANCH_ID', 'BRANCH_ID must not be NULL', 'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN BRANCH_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES', 0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP())
INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES
  (2, 'BR_NULL_BRANCH_NAME', 'COMPLETENESS', 'ON_DEMAND', 'HIGH', 'BANKING_DQ_DB.RAW', 'BRANCHES', 'BRANCH_NAME', 'BRANCH_NAME must not be NULL', 'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN BRANCH_NAME IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES', 0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP())
INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES
  (3, 'BR_NULL_IFSC_CODE', 'COMPLETENESS', 'ON_DEMAND', 'HIGH', 'BANKING_DQ_DB.RAW', 'BRANCHES', 'IFSC_CODE', 'IFSC_CODE must not be NULL', 'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN IFSC_CODE IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES', 0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP())
INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES
  (4, 'BR_UNIQUE_BRANCH_ID', 'UNIQUENESS', 'ON_DEMAND', 'HIGH', 'BANKING_DQ_DB.RAW', 'BRANCHES', 'BRANCH_ID', 'BRANCH_ID must be unique (primary key)', 'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, COUNT(*) - COUNT(DISTINCT BRANCH_ID) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES', 0, '["uniqueness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP())
INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES
  (5, 'BR_UNIQUE_IFSC', 'UNIQUENESS', 'ON_DEMAND', 'HIGH', 'BANKING_DQ_DB.RAW', 'BRANCHES', 'IFSC_CODE', 'IFSC_CODE must be unique per branch', 'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, COUNT(*) - COUNT(DISTINCT IFSC_CODE) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES', 0, '["uniqueness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP())
INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES
  (6, 'BR_IFSC_FORMAT', 'VALIDITY', 'ON_DEMAND', 'MEDIUM', 'BANKING_DQ_DB.RAW', 'BRANCHES', 'IFSC_CODE', 'IFSC must match format: 4 alpha + 0 + 6 alphanum', 'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN IFSC_CODE IS NOT NULL AND NOT RLIKE(IFSC_CODE, ''^[A-Z]{4}0[A-Z0-9]{6}$'') THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES', 0, '["validity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP())
INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES
  (7, 'BR_VALID_IS_ACTIVE', 'COMPLETENESS', 'ON_DEMAND', 'MEDIUM', 'BANKING_DQ_DB.RAW', 'BRANCHES', 'IS_ACTIVE', 'IS_ACTIVE must not be NULL', 'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN IS_ACTIVE IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES', 0, '["validity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP())
INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES
  (8, 'BR_ROW_COUNT', 'VOLUME', 'ON_DEMAND', 'MEDIUM', 'BANKING_DQ_DB.RAW', 'BRANCHES', NULL, 'Table row count must be > 0', 'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES', 0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP())
INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES
  (9, 'BR_FRESHNESS', 'TIMELINESS', 'ON_DEMAND', 'LOW', 'BANKING_DQ_DB.RAW', 'BRANCHES', 'CREATED_AT', 'Data freshness: most recent CREATED_AT within 30 days', 'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, CASE WHEN DATEDIFF(''DAY'', MAX(CREATED_AT), CURRENT_TIMESTAMP()) > 30 THEN 1 ELSE 0 END AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES', 0, '["timeliness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP())
SELECT 1 FROM DUAL;

-- NOTE: CUSTOMERS (10-22), ACCOUNTS (23-35), TRANSACTIONS (36-48), 
-- LOAN_APPLICATIONS (49-63) INSERT statements are identical to those
-- in DQ_Rules.sql — run that file after creating these tables.

-- ============================================================================
-- 4. VERIFICATION
-- ============================================================================

-- Verify table creation
SELECT TABLE_NAME, ROW_COUNT 
FROM BANKING_DQ_DB.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'DQ_MONITORING' 
ORDER BY TABLE_NAME;

-- Verify rule loading summary
SELECT TABLE_NM, CRITICALITY, COUNT(*) AS RULE_COUNT 
FROM BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG 
WHERE IS_ACTIVE = TRUE 
GROUP BY TABLE_NM, CRITICALITY 
ORDER BY TABLE_NM, CRITICALITY;

-- Verify rule type distribution
SELECT RULE_TYPE, COUNT(*) AS CNT 
FROM BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG 
GROUP BY RULE_TYPE 
ORDER BY CNT DESC;

/*=============================================================================
  END OF FRAMEWORK CONFIG SCRIPT
=============================================================================*/
