/*=============================================================================
  DQ_Rules.sql
  Data Quality Framework — Step 3: Data Quality Rules
  Database: BANKING_DQ_DB  |  Schema: RAW
  
  Approach: SQL-based rules engine (Standard Edition compatible)
  Each rule is a SQL query returning FAILED_RECORD_COUNT and TOTAL_RECORD_COUNT.
  Rules are loaded into DQ_RULE_CONFIG (created in Step 4) and executed
  by the orchestration stored procedure (Step 5).
  
  63 Rules across 5 tables, 7 DQ dimensions:
    Completeness, Uniqueness, Validity, Accuracy, Consistency,
    Referential Integrity, Timeliness/Freshness
  
  NOTE: DMF-equivalent DDL is included at the bottom as reference
  for future Enterprise Edition upgrade.
=============================================================================*/

-- ============================================================================
-- SECTION A: SQL-BASED RULE DEFINITIONS
-- Each rule is an INSERT into BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG
-- The RULE_SQL column contains a query that returns:
--   TOTAL_RECORD_COUNT, FAILED_RECORD_COUNT
-- ============================================================================

-- Prerequisites: Run Step 4 (DQ_Framework_Config.sql) first to create the tables.

USE DATABASE BANKING_DQ_DB;
USE SCHEMA DQ_MONITORING;

-- ============================================================================
-- TABLE 1: BRANCHES — 9 Rules
-- ============================================================================

-- Rule 1: BR_NULL_BRANCH_ID (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  1, 'BR_NULL_BRANCH_ID', 'COMPLETENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'BRANCHES', 'BRANCH_ID',
  'BRANCH_ID must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN BRANCH_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 2: BR_NULL_BRANCH_NAME (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  2, 'BR_NULL_BRANCH_NAME', 'COMPLETENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'BRANCHES', 'BRANCH_NAME',
  'BRANCH_NAME must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN BRANCH_NAME IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 3: BR_NULL_IFSC_CODE (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  3, 'BR_NULL_IFSC_CODE', 'COMPLETENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'BRANCHES', 'IFSC_CODE',
  'IFSC_CODE must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN IFSC_CODE IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 4: BR_UNIQUE_BRANCH_ID (Uniqueness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  4, 'BR_UNIQUE_BRANCH_ID', 'UNIQUENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'BRANCHES', 'BRANCH_ID',
  'BRANCH_ID must be unique (primary key)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, COUNT(*) - COUNT(DISTINCT BRANCH_ID) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES',
  0, '["uniqueness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 5: BR_UNIQUE_IFSC (Uniqueness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  5, 'BR_UNIQUE_IFSC', 'UNIQUENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'BRANCHES', 'IFSC_CODE',
  'IFSC_CODE must be unique per branch',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, COUNT(*) - COUNT(DISTINCT IFSC_CODE) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES',
  0, '["uniqueness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 6: BR_IFSC_FORMAT (Validity | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  6, 'BR_IFSC_FORMAT', 'VALIDITY', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'BRANCHES', 'IFSC_CODE',
  'IFSC must match format: 4 alpha + 0 + 6 alphanum (^[A-Z]{4}0[A-Z0-9]{6}$)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN IFSC_CODE IS NOT NULL AND NOT RLIKE(IFSC_CODE, ''^[A-Z]{4}0[A-Z0-9]{6}$'') THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES',
  0, '["validity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 7: BR_VALID_IS_ACTIVE (Validity | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  7, 'BR_VALID_IS_ACTIVE', 'COMPLETENESS', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'BRANCHES', 'IS_ACTIVE',
  'IS_ACTIVE must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN IS_ACTIVE IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES',
  0, '["validity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 8: BR_ROW_COUNT (Completeness | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  8, 'BR_ROW_COUNT', 'VOLUME', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'BRANCHES', NULL,
  'Table row count must be > 0',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 9: BR_FRESHNESS (Timeliness | LOW)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  9, 'BR_FRESHNESS', 'TIMELINESS', 'ON_DEMAND', 'LOW',
  'BANKING_DQ_DB.RAW', 'BRANCHES', 'CREATED_AT',
  'Data freshness: most recent CREATED_AT should be within 30 days',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, CASE WHEN DATEDIFF(''DAY'', MAX(CREATED_AT), CURRENT_TIMESTAMP()) > 30 THEN 1 ELSE 0 END AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.BRANCHES',
  0, '["timeliness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- ============================================================================
-- TABLE 2: CUSTOMERS — 13 Rules
-- ============================================================================

-- Rule 10: CU_NULL_CUSTOMER_ID (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  10, 'CU_NULL_CUSTOMER_ID', 'COMPLETENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'CUSTOMERS', 'CUSTOMER_ID',
  'CUSTOMER_ID must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.CUSTOMERS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 11: CU_NULL_EMAIL (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  11, 'CU_NULL_EMAIL', 'COMPLETENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'CUSTOMERS', 'EMAIL',
  'EMAIL must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN EMAIL IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.CUSTOMERS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 12: CU_NULL_FIRST_NAME (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  12, 'CU_NULL_FIRST_NAME', 'COMPLETENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'CUSTOMERS', 'FIRST_NAME',
  'FIRST_NAME must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN FIRST_NAME IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.CUSTOMERS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 13: CU_UNIQUE_CUSTOMER_ID (Uniqueness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  13, 'CU_UNIQUE_CUSTOMER_ID', 'UNIQUENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'CUSTOMERS', 'CUSTOMER_ID',
  'CUSTOMER_ID must be unique (primary key)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, COUNT(*) - COUNT(DISTINCT CUSTOMER_ID) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.CUSTOMERS',
  0, '["uniqueness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 14: CU_UNIQUE_EMAIL (Uniqueness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  14, 'CU_UNIQUE_EMAIL', 'UNIQUENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'CUSTOMERS', 'EMAIL',
  'EMAIL must be unique per customer',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, COUNT(*) - COUNT(DISTINCT EMAIL) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.CUSTOMERS',
  0, '["uniqueness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 15: CU_EMAIL_FORMAT (Validity | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  15, 'CU_EMAIL_FORMAT', 'VALIDITY', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'CUSTOMERS', 'EMAIL',
  'EMAIL must contain @ with valid domain format',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN EMAIL IS NOT NULL AND NOT RLIKE(EMAIL, ''^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'') THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.CUSTOMERS',
  0, '["validity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 16: CU_VALID_KYC_STATUS (Validity | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  16, 'CU_VALID_KYC_STATUS', 'VALIDITY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'CUSTOMERS', 'KYC_STATUS',
  'KYC_STATUS must be in (VERIFIED, PENDING, REJECTED)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN KYC_STATUS NOT IN (''VERIFIED'', ''PENDING'', ''REJECTED'') THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.CUSTOMERS',
  0, '["validity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 17: CU_VALID_RISK_CATEGORY (Validity | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  17, 'CU_VALID_RISK_CATEGORY', 'VALIDITY', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'CUSTOMERS', 'RISK_CATEGORY',
  'RISK_CATEGORY must be in (LOW, MEDIUM, HIGH)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN RISK_CATEGORY NOT IN (''LOW'', ''MEDIUM'', ''HIGH'') THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.CUSTOMERS',
  0, '["validity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 18: CU_DOB_NOT_FUTURE (Accuracy | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  18, 'CU_DOB_NOT_FUTURE', 'ACCURACY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'CUSTOMERS', 'DATE_OF_BIRTH',
  'DATE_OF_BIRTH must not be in the future',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN DATE_OF_BIRTH IS NOT NULL AND DATE_OF_BIRTH > CURRENT_DATE() THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.CUSTOMERS',
  0, '["accuracy"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 19: CU_DOB_REASONABLE_AGE (Accuracy | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  19, 'CU_DOB_REASONABLE_AGE', 'ACCURACY', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'CUSTOMERS', 'DATE_OF_BIRTH',
  'Customer age must be between 18 and 120 years',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN DATE_OF_BIRTH IS NOT NULL AND (DATEDIFF(''YEAR'', DATE_OF_BIRTH, CURRENT_DATE()) < 18 OR DATEDIFF(''YEAR'', DATE_OF_BIRTH, CURRENT_DATE()) > 120) THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.CUSTOMERS',
  0, '["accuracy"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 20: CU_FK_BRANCH_ID (Referential Integrity | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  20, 'CU_FK_BRANCH_ID', 'REFERENTIAL_INTEGRITY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'CUSTOMERS', 'BRANCH_ID',
  'BRANCH_ID must exist in BRANCHES table',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN c.BRANCH_ID IS NOT NULL AND b.BRANCH_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.CUSTOMERS c LEFT JOIN BANKING_DQ_DB.RAW.BRANCHES b ON c.BRANCH_ID = b.BRANCH_ID',
  0, '["referential_integrity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 21: CU_ROW_COUNT (Completeness | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  21, 'CU_ROW_COUNT', 'VOLUME', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'CUSTOMERS', NULL,
  'Table row count must be > 0',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.CUSTOMERS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 22: CU_FRESHNESS (Timeliness | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  22, 'CU_FRESHNESS', 'TIMELINESS', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'CUSTOMERS', 'CREATED_AT',
  'Data freshness: most recent CREATED_AT should be within 30 days',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, CASE WHEN DATEDIFF(''DAY'', MAX(CREATED_AT), CURRENT_TIMESTAMP()) > 30 THEN 1 ELSE 0 END AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.CUSTOMERS',
  0, '["timeliness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- ============================================================================
-- TABLE 3: ACCOUNTS — 13 Rules
-- ============================================================================

-- Rule 23: AC_NULL_ACCOUNT_ID (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  23, 'AC_NULL_ACCOUNT_ID', 'COMPLETENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'ACCOUNTS', 'ACCOUNT_ID',
  'ACCOUNT_ID must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN ACCOUNT_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.ACCOUNTS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 24: AC_NULL_CUSTOMER_ID (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  24, 'AC_NULL_CUSTOMER_ID', 'COMPLETENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'ACCOUNTS', 'CUSTOMER_ID',
  'CUSTOMER_ID must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.ACCOUNTS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 25: AC_NULL_BALANCE (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  25, 'AC_NULL_BALANCE', 'COMPLETENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'ACCOUNTS', 'BALANCE',
  'BALANCE must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN BALANCE IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.ACCOUNTS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 26: AC_UNIQUE_ACCOUNT_ID (Uniqueness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  26, 'AC_UNIQUE_ACCOUNT_ID', 'UNIQUENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'ACCOUNTS', 'ACCOUNT_ID',
  'ACCOUNT_ID must be unique (primary key)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, COUNT(*) - COUNT(DISTINCT ACCOUNT_ID) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.ACCOUNTS',
  0, '["uniqueness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 27: AC_VALID_ACCOUNT_TYPE (Validity | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  27, 'AC_VALID_ACCOUNT_TYPE', 'VALIDITY', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'ACCOUNTS', 'ACCOUNT_TYPE',
  'ACCOUNT_TYPE must be in (SAVINGS, CURRENT, LOAN)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN ACCOUNT_TYPE NOT IN (''SAVINGS'', ''CURRENT'', ''LOAN'') THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.ACCOUNTS',
  0, '["validity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 28: AC_VALID_ACCOUNT_STATUS (Validity | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  28, 'AC_VALID_ACCOUNT_STATUS', 'VALIDITY', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'ACCOUNTS', 'ACCOUNT_STATUS',
  'ACCOUNT_STATUS must be in (ACTIVE, DORMANT, CLOSED)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN ACCOUNT_STATUS NOT IN (''ACTIVE'', ''DORMANT'', ''CLOSED'') THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.ACCOUNTS',
  0, '["validity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 29: AC_VALID_CURRENCY (Validity | LOW)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  29, 'AC_VALID_CURRENCY', 'VALIDITY', 'ON_DEMAND', 'LOW',
  'BANKING_DQ_DB.RAW', 'ACCOUNTS', 'CURRENCY',
  'CURRENCY must be in (INR, USD)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN CURRENCY NOT IN (''INR'', ''USD'') THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.ACCOUNTS',
  0, '["validity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 30: AC_SAVINGS_BAL_NON_NEG (Accuracy | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  30, 'AC_SAVINGS_BAL_NON_NEG', 'ACCURACY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'ACCOUNTS', 'BALANCE',
  'SAVINGS account balance must be >= 0',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN ACCOUNT_TYPE = ''SAVINGS'' AND BALANCE < 0 THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.ACCOUNTS',
  0, '["accuracy"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 31: AC_OPEN_DATE_NOT_FUTURE (Accuracy | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  31, 'AC_OPEN_DATE_NOT_FUTURE', 'ACCURACY', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'ACCOUNTS', 'OPEN_DATE',
  'OPEN_DATE must not be in the future',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN OPEN_DATE IS NOT NULL AND OPEN_DATE > CURRENT_DATE() THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.ACCOUNTS',
  0, '["accuracy"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 32: AC_FK_CUSTOMER_ID (Referential Integrity | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  32, 'AC_FK_CUSTOMER_ID', 'REFERENTIAL_INTEGRITY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'ACCOUNTS', 'CUSTOMER_ID',
  'CUSTOMER_ID must exist in CUSTOMERS table',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN a.CUSTOMER_ID IS NOT NULL AND c.CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.ACCOUNTS a LEFT JOIN BANKING_DQ_DB.RAW.CUSTOMERS c ON a.CUSTOMER_ID = c.CUSTOMER_ID',
  0, '["referential_integrity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 33: AC_FK_BRANCH_ID (Referential Integrity | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  33, 'AC_FK_BRANCH_ID', 'REFERENTIAL_INTEGRITY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'ACCOUNTS', 'BRANCH_ID',
  'BRANCH_ID must exist in BRANCHES table',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN a.BRANCH_ID IS NOT NULL AND b.BRANCH_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.ACCOUNTS a LEFT JOIN BANKING_DQ_DB.RAW.BRANCHES b ON a.BRANCH_ID = b.BRANCH_ID',
  0, '["referential_integrity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 34: AC_ROW_COUNT (Completeness | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  34, 'AC_ROW_COUNT', 'VOLUME', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'ACCOUNTS', NULL,
  'Table row count must be > 0',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.ACCOUNTS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 35: AC_FRESHNESS (Timeliness | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  35, 'AC_FRESHNESS', 'TIMELINESS', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'ACCOUNTS', 'CREATED_AT',
  'Data freshness: most recent CREATED_AT should be within 30 days',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, CASE WHEN DATEDIFF(''DAY'', MAX(CREATED_AT), CURRENT_TIMESTAMP()) > 30 THEN 1 ELSE 0 END AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.ACCOUNTS',
  0, '["timeliness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- ============================================================================
-- TABLE 4: TRANSACTIONS — 13 Rules
-- ============================================================================

-- Rule 36: TX_NULL_TXN_ID (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  36, 'TX_NULL_TXN_ID', 'COMPLETENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'TRANSACTIONS', 'TRANSACTION_ID',
  'TRANSACTION_ID must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN TRANSACTION_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.TRANSACTIONS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 37: TX_NULL_ACCOUNT_ID (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  37, 'TX_NULL_ACCOUNT_ID', 'COMPLETENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'TRANSACTIONS', 'ACCOUNT_ID',
  'ACCOUNT_ID must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN ACCOUNT_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.TRANSACTIONS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 38: TX_NULL_AMOUNT (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  38, 'TX_NULL_AMOUNT', 'COMPLETENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'TRANSACTIONS', 'AMOUNT',
  'AMOUNT must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN AMOUNT IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.TRANSACTIONS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 39: TX_UNIQUE_TXN_ID (Uniqueness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  39, 'TX_UNIQUE_TXN_ID', 'UNIQUENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'TRANSACTIONS', 'TRANSACTION_ID',
  'TRANSACTION_ID must be unique (primary key)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, COUNT(*) - COUNT(DISTINCT TRANSACTION_ID) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.TRANSACTIONS',
  0, '["uniqueness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 40: TX_AMOUNT_POSITIVE (Accuracy | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  40, 'TX_AMOUNT_POSITIVE', 'ACCURACY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'TRANSACTIONS', 'AMOUNT',
  'Transaction amount must be > 0',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN AMOUNT IS NOT NULL AND AMOUNT <= 0 THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.TRANSACTIONS',
  0, '["accuracy"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 41: TX_AMOUNT_RANGE (Accuracy | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  41, 'TX_AMOUNT_RANGE', 'ACCURACY', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'TRANSACTIONS', 'AMOUNT',
  'Transaction amount must be within 0 to 10,000,000',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN AMOUNT IS NOT NULL AND (AMOUNT < 0 OR AMOUNT > 10000000) THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.TRANSACTIONS',
  0, '["accuracy"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 42: TX_VALID_TXN_TYPE (Validity | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  42, 'TX_VALID_TXN_TYPE', 'VALIDITY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'TRANSACTIONS', 'TRANSACTION_TYPE',
  'TRANSACTION_TYPE must be in (DEBIT, CREDIT, TRANSFER)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN TRANSACTION_TYPE NOT IN (''DEBIT'', ''CREDIT'', ''TRANSFER'') THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.TRANSACTIONS',
  0, '["validity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 43: TX_VALID_TXN_STATUS (Validity | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  43, 'TX_VALID_TXN_STATUS', 'VALIDITY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'TRANSACTIONS', 'TRANSACTION_STATUS',
  'TRANSACTION_STATUS must be in (SUCCESS, FAILED, PENDING)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN TRANSACTION_STATUS NOT IN (''SUCCESS'', ''FAILED'', ''PENDING'') THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.TRANSACTIONS',
  0, '["validity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 44: TX_VALID_CHANNEL (Validity | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  44, 'TX_VALID_CHANNEL', 'VALIDITY', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'TRANSACTIONS', 'CHANNEL',
  'CHANNEL must be in (UPI, CARD, NEFT, IMPS, ATM, CHEQUE, RTGS)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN CHANNEL NOT IN (''UPI'', ''CARD'', ''NEFT'', ''IMPS'', ''ATM'', ''CHEQUE'', ''RTGS'') THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.TRANSACTIONS',
  0, '["validity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 45: TX_DATE_NOT_FUTURE (Accuracy | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  45, 'TX_DATE_NOT_FUTURE', 'ACCURACY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'TRANSACTIONS', 'TRANSACTION_DATE',
  'Transaction date must not be in the future',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN TRANSACTION_DATE IS NOT NULL AND TRANSACTION_DATE > CURRENT_TIMESTAMP() THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.TRANSACTIONS',
  0, '["accuracy"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 46: TX_FK_ACCOUNT_ID (Referential Integrity | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  46, 'TX_FK_ACCOUNT_ID', 'REFERENTIAL_INTEGRITY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'TRANSACTIONS', 'ACCOUNT_ID',
  'ACCOUNT_ID must exist in ACCOUNTS table',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN t.ACCOUNT_ID IS NOT NULL AND a.ACCOUNT_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.TRANSACTIONS t LEFT JOIN BANKING_DQ_DB.RAW.ACCOUNTS a ON t.ACCOUNT_ID = a.ACCOUNT_ID',
  0, '["referential_integrity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 47: TX_ROW_COUNT (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  47, 'TX_ROW_COUNT', 'VOLUME', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'TRANSACTIONS', NULL,
  'Table row count must be > 0 (high-volume financial table)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.TRANSACTIONS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 48: TX_FRESHNESS (Timeliness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  48, 'TX_FRESHNESS', 'TIMELINESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'TRANSACTIONS', 'TRANSACTION_DATE',
  'Data freshness: most recent TRANSACTION_DATE should be within 7 days',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, CASE WHEN DATEDIFF(''DAY'', MAX(TRANSACTION_DATE), CURRENT_TIMESTAMP()) > 7 THEN 1 ELSE 0 END AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.TRANSACTIONS',
  0, '["timeliness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- ============================================================================
-- TABLE 5: LOAN_APPLICATIONS — 15 Rules
-- ============================================================================

-- Rule 49: LA_NULL_APP_ID (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  49, 'LA_NULL_APP_ID', 'COMPLETENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'LOAN_APPLICATIONS', 'APPLICATION_ID',
  'APPLICATION_ID must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN APPLICATION_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 50: LA_NULL_CUSTOMER_ID (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  50, 'LA_NULL_CUSTOMER_ID', 'COMPLETENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'LOAN_APPLICATIONS', 'CUSTOMER_ID',
  'CUSTOMER_ID must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 51: LA_NULL_REQUESTED_AMT (Completeness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  51, 'LA_NULL_REQUESTED_AMT', 'COMPLETENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'LOAN_APPLICATIONS', 'REQUESTED_AMOUNT',
  'REQUESTED_AMOUNT must not be NULL',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN REQUESTED_AMOUNT IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 52: LA_UNIQUE_APP_ID (Uniqueness | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  52, 'LA_UNIQUE_APP_ID', 'UNIQUENESS', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'LOAN_APPLICATIONS', 'APPLICATION_ID',
  'APPLICATION_ID must be unique (primary key)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, COUNT(*) - COUNT(DISTINCT APPLICATION_ID) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',
  0, '["uniqueness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 53: LA_REQUESTED_AMT_POSITIVE (Accuracy | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  53, 'LA_REQUESTED_AMT_POSITIVE', 'ACCURACY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'LOAN_APPLICATIONS', 'REQUESTED_AMOUNT',
  'Requested amount must be > 0',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN REQUESTED_AMOUNT IS NOT NULL AND REQUESTED_AMOUNT <= 0 THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',
  0, '["accuracy"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 54: LA_APPROVED_LEQ_REQUESTED (Accuracy | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  54, 'LA_APPROVED_LEQ_REQUESTED', 'ACCURACY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'LOAN_APPLICATIONS', 'APPROVED_AMOUNT',
  'Approved amount must not exceed requested amount',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN APPROVED_AMOUNT IS NOT NULL AND REQUESTED_AMOUNT IS NOT NULL AND APPROVED_AMOUNT > REQUESTED_AMOUNT THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',
  0, '["accuracy"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 55: LA_APPROVED_NULL_IF_NOT_OK (Consistency | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  55, 'LA_APPROVED_NULL_IF_NOT_OK', 'CONSISTENCY', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'LOAN_APPLICATIONS', 'APPROVED_AMOUNT',
  'APPROVED_AMOUNT should be NULL when STATUS is PENDING or REJECTED',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN APPLICATION_STATUS IN (''PENDING'', ''REJECTED'') AND APPROVED_AMOUNT IS NOT NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',
  0, '["consistency"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 56: LA_VALID_LOAN_TYPE (Validity | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  56, 'LA_VALID_LOAN_TYPE', 'VALIDITY', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'LOAN_APPLICATIONS', 'LOAN_TYPE',
  'LOAN_TYPE must be in (HOME, PERSONAL, CAR, EDUCATION, BUSINESS)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN LOAN_TYPE NOT IN (''HOME'', ''PERSONAL'', ''CAR'', ''EDUCATION'', ''BUSINESS'') THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',
  0, '["validity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 57: LA_VALID_APP_STATUS (Validity | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  57, 'LA_VALID_APP_STATUS', 'VALIDITY', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'LOAN_APPLICATIONS', 'APPLICATION_STATUS',
  'APPLICATION_STATUS must be in (PENDING, APPROVED, REJECTED)',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN APPLICATION_STATUS NOT IN (''PENDING'', ''APPROVED'', ''REJECTED'') THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',
  0, '["validity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 58: LA_CREDIT_SCORE_RANGE (Accuracy | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  58, 'LA_CREDIT_SCORE_RANGE', 'ACCURACY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'LOAN_APPLICATIONS', 'CREDIT_SCORE',
  'Credit score must be between 300 and 900',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN CREDIT_SCORE IS NOT NULL AND (CREDIT_SCORE < 300 OR CREDIT_SCORE > 900) THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',
  0, '["accuracy"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 59: LA_APP_DATE_NOT_FUTURE (Accuracy | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  59, 'LA_APP_DATE_NOT_FUTURE', 'ACCURACY', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'LOAN_APPLICATIONS', 'APPLICATION_DATE',
  'Application date must not be in the future',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN APPLICATION_DATE IS NOT NULL AND APPLICATION_DATE > CURRENT_DATE() THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',
  0, '["accuracy"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 60: LA_FK_CUSTOMER_ID (Referential Integrity | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  60, 'LA_FK_CUSTOMER_ID', 'REFERENTIAL_INTEGRITY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'LOAN_APPLICATIONS', 'CUSTOMER_ID',
  'CUSTOMER_ID must exist in CUSTOMERS table',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN l.CUSTOMER_ID IS NOT NULL AND c.CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS l LEFT JOIN BANKING_DQ_DB.RAW.CUSTOMERS c ON l.CUSTOMER_ID = c.CUSTOMER_ID',
  0, '["referential_integrity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 61: LA_FK_BRANCH_ID (Referential Integrity | HIGH)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  61, 'LA_FK_BRANCH_ID', 'REFERENTIAL_INTEGRITY', 'ON_DEMAND', 'HIGH',
  'BANKING_DQ_DB.RAW', 'LOAN_APPLICATIONS', 'BRANCH_ID',
  'BRANCH_ID must exist in BRANCHES table',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, SUM(CASE WHEN l.BRANCH_ID IS NOT NULL AND b.BRANCH_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS l LEFT JOIN BANKING_DQ_DB.RAW.BRANCHES b ON l.BRANCH_ID = b.BRANCH_ID',
  0, '["referential_integrity"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 62: LA_ROW_COUNT (Completeness | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  62, 'LA_ROW_COUNT', 'VOLUME', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'LOAN_APPLICATIONS', NULL,
  'Table row count must be > 0',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',
  0, '["completeness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Rule 63: LA_FRESHNESS (Timeliness | MEDIUM)
INSERT INTO DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
  63, 'LA_FRESHNESS', 'TIMELINESS', 'ON_DEMAND', 'MEDIUM',
  'BANKING_DQ_DB.RAW', 'LOAN_APPLICATIONS', 'CREATED_AT',
  'Data freshness: most recent CREATED_AT should be within 30 days',
  'SELECT COUNT(*) AS TOTAL_RECORD_COUNT, CASE WHEN DATEDIFF(''DAY'', MAX(CREATED_AT), CURRENT_TIMESTAMP()) > 30 THEN 1 ELSE 0 END AS FAILED_RECORD_COUNT FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',
  0, '["timeliness"]', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);


-- ============================================================================
-- SECTION B: DMF REFERENCE SCRIPT (Enterprise Edition — for future upgrade)
-- These statements require Enterprise Edition to execute.
-- ============================================================================

/*
-- Set schedule on all tables
ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

-- ============================================================================
-- System DMFs: NULL_COUNT
-- ============================================================================
ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (BRANCH_ID);
ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (BRANCH_NAME);
ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (IFSC_CODE);
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (EMAIL);
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (FIRST_NAME);
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ACCOUNT_ID);
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (BALANCE);
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (TRANSACTION_ID);
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ACCOUNT_ID);
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (AMOUNT);
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (APPLICATION_ID);
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (REQUESTED_AMOUNT);

-- ============================================================================
-- System DMFs: DUPLICATE_COUNT
-- ============================================================================
ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (BRANCH_ID);
ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (IFSC_CODE);
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (CUSTOMER_ID);
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (EMAIL);
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (ACCOUNT_ID);
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (TRANSACTION_ID);
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (APPLICATION_ID);

-- ============================================================================
-- System DMFs: ROW_COUNT & FRESHNESS
-- ============================================================================
ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (CREATED_AT);
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (CREATED_AT);
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (CREATED_AT);
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (TRANSACTION_DATE);
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (CREATED_AT);

-- ============================================================================
-- System DMFs: FUTURE_TIMESTAMP_COUNT
-- ============================================================================
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FUTURE_TIMESTAMP_COUNT ON (DATE_OF_BIRTH);
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FUTURE_TIMESTAMP_COUNT ON (TRANSACTION_DATE);

-- ============================================================================
-- System DMFs: NEGATIVE_COUNT
-- ============================================================================
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NEGATIVE_COUNT ON (AMOUNT);

-- ============================================================================
-- System DMFs: ACCEPTED_VALUES (categorical validation)
-- ============================================================================
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (KYC_STATUS, KYC_STATUS -> KYC_STATUS IN ('VERIFIED', 'PENDING', 'REJECTED'));
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (RISK_CATEGORY, RISK_CATEGORY -> RISK_CATEGORY IN ('LOW', 'MEDIUM', 'HIGH'));
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (ACCOUNT_TYPE, ACCOUNT_TYPE -> ACCOUNT_TYPE IN ('SAVINGS', 'CURRENT', 'LOAN'));
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (ACCOUNT_STATUS, ACCOUNT_STATUS -> ACCOUNT_STATUS IN ('ACTIVE', 'DORMANT', 'CLOSED'));
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (CURRENCY, CURRENCY -> CURRENCY IN ('INR', 'USD'));
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (TRANSACTION_TYPE, TRANSACTION_TYPE -> TRANSACTION_TYPE IN ('DEBIT', 'CREDIT', 'TRANSFER'));
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (TRANSACTION_STATUS, TRANSACTION_STATUS -> TRANSACTION_STATUS IN ('SUCCESS', 'FAILED', 'PENDING'));
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (CHANNEL, CHANNEL -> CHANNEL IN ('UPI', 'CARD', 'NEFT', 'IMPS', 'ATM', 'CHEQUE', 'RTGS'));
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (LOAN_TYPE, LOAN_TYPE -> LOAN_TYPE IN ('HOME', 'PERSONAL', 'CAR', 'EDUCATION', 'BUSINESS'));
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (APPLICATION_STATUS, APPLICATION_STATUS -> APPLICATION_STATUS IN ('PENDING', 'APPROVED', 'REJECTED'));

-- ============================================================================
-- Custom DMFs (require Enterprise Edition to CREATE)
-- ============================================================================

-- IFSC format validation
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_IFSC_FORMAT_CHECK(
  ARG_T TABLE(ARG_C STRING)) RETURNS NUMBER AS
$$ SELECT COUNT(*) FROM ARG_T WHERE ARG_C IS NOT NULL AND NOT RLIKE(ARG_C, '^[A-Z]{4}0[A-Z0-9]{6}$') $$;
ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_IFSC_FORMAT_CHECK ON (IFSC_CODE);

-- Email format validation
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_EMAIL_FORMAT_CHECK(
  ARG_T TABLE(ARG_C STRING)) RETURNS NUMBER AS
$$ SELECT COUNT(*) FROM ARG_T WHERE ARG_C IS NOT NULL AND NOT RLIKE(ARG_C, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$') $$;
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_EMAIL_FORMAT_CHECK ON (EMAIL);

-- DOB reasonable age (18-120)
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_DOB_REASONABLE_AGE(
  ARG_T TABLE(ARG_C DATE)) RETURNS NUMBER AS
$$ SELECT COUNT(*) FROM ARG_T WHERE ARG_C IS NOT NULL AND (DATEDIFF('YEAR', ARG_C, CURRENT_DATE()) < 18 OR DATEDIFF('YEAR', ARG_C, CURRENT_DATE()) > 120) $$;
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_DOB_REASONABLE_AGE ON (DATE_OF_BIRTH);

-- Savings balance non-negative
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_SAVINGS_BAL_NON_NEG(
  ARG_T TABLE(ARG_BALANCE NUMBER(18,2), ARG_TYPE STRING)) RETURNS NUMBER AS
$$ SELECT COUNT(*) FROM ARG_T WHERE ARG_TYPE = 'SAVINGS' AND ARG_BALANCE < 0 $$;
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_SAVINGS_BAL_NON_NEG ON (BALANCE, ACCOUNT_TYPE);

-- Amount positive check
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_AMOUNT_POSITIVE(
  ARG_T TABLE(ARG_C NUMBER(18,2))) RETURNS NUMBER AS
$$ SELECT COUNT(*) FROM ARG_T WHERE ARG_C IS NOT NULL AND ARG_C <= 0 $$;
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_AMOUNT_POSITIVE ON (AMOUNT);

-- Loan approved <= requested
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_APPROVED_LEQ_REQUESTED(
  ARG_T TABLE(ARG_APPROVED NUMBER(18,2), ARG_REQUESTED NUMBER(18,2))) RETURNS NUMBER AS
$$ SELECT COUNT(*) FROM ARG_T WHERE ARG_APPROVED IS NOT NULL AND ARG_REQUESTED IS NOT NULL AND ARG_APPROVED > ARG_REQUESTED $$;
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_APPROVED_LEQ_REQUESTED ON (APPROVED_AMOUNT, REQUESTED_AMOUNT);

-- Credit score range (300-900)
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_CREDIT_SCORE_RANGE(
  ARG_T TABLE(ARG_C NUMBER(5,0))) RETURNS NUMBER AS
$$ SELECT COUNT(*) FROM ARG_T WHERE ARG_C IS NOT NULL AND (ARG_C < 300 OR ARG_C > 900) $$;
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_CREDIT_SCORE_RANGE ON (CREDIT_SCORE);

-- Approved NULL when not approved
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_APPROVED_NULL_CONSISTENCY(
  ARG_T TABLE(ARG_AMT NUMBER(18,2), ARG_STATUS STRING)) RETURNS NUMBER AS
$$ SELECT COUNT(*) FROM ARG_T WHERE ARG_STATUS IN ('PENDING', 'REJECTED') AND ARG_AMT IS NOT NULL $$;
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_APPROVED_NULL_CONSISTENCY ON (APPROVED_AMOUNT, APPLICATION_STATUS);

-- Referential integrity: CUSTOMERS.BRANCH_ID -> BRANCHES
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_FK_CUSTOMER_BRANCH(
  ARG_T1 TABLE(ARG_C1 STRING), ARG_T2 TABLE(ARG_C2 STRING)) RETURNS NUMBER AS
$$ SELECT COUNT(*) FROM ARG_T1 WHERE ARG_C1 IS NOT NULL AND ARG_C1 NOT IN (SELECT ARG_C2 FROM ARG_T2) $$;
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_FK_CUSTOMER_BRANCH ON (BRANCH_ID) REFERENCES BANKING_DQ_DB.RAW.BRANCHES ON (BRANCH_ID);

*/

/*=============================================================================
  END OF DQ RULES SCRIPT
  
  Section A: 63 INSERT statements for DQ_RULE_CONFIG (execute after Step 4)
  Section B: DMF reference DDL (requires Enterprise Edition upgrade)
=============================================================================*/
